language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

services:
  - elasticsearch

before_script:
  - sleep 10
  - phpenv rehash

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.4.deb && sudo service elasticsearch restart

env:
  global:
    - PHPUNIT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: CODECOVERAGE=1 PHPUNIT=0

install:
  - composer self-update
  - composer install --no-interaction

script:
  - sh -c "if [ '$PHPUNIT' = '1' ]; then vendor/bin/phpunit; fi"

  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then vendor/phpunit/phpunit/phpunit --coverage-clover=clover.xml || true; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then wget -O codecov.sh https://codecov.io/bash; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then bash codecov.sh; fi"

notifications:
  email: false
