name: Pull Request

on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
      - name: PHP Version
        run: php -v
      - name: Install
        run: |
          composer self-update
          composer install --prefer-dist --no-progress
